{
 "title": "ASR9K",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Packets per second MgmtEth0/RP0/CPU0/0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco_mdt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"MgmtEth0/RP0/CPU0/0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_received\" or r[\"_field\"] == \"packets_sent\")\r\n      |> difference()\r\n      |> map(fn: (r) => ({r with _value: float(v: r._value) / 30.0}))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco_mdt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-shellutil-oper:system-time/uptime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n      |> map(fn: (r) => ({r with _value: r._value / 60}))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"cisco_mdt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"process_cpu/process_cpu_one_minute\")\r\n  |> group(columns: [\"source\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco_mdt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_memory\" or r[\"_field\"] == \"free_physical_memory\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  }
 ]
}